// Generated by CoffeeScript 1.6.2
(function() {
  var FILES, Images, currentIndex, sizeToFit, toggleLoading, viewer;

  FILES = window.FILES;

  viewer = $('#viewer');

  currentIndex = 0;

  Images = {
    current: function() {
      $('#slide-current').text(currentIndex + 1);
      return FILES[currentIndex];
    },
    next: function() {
      if (currentIndex < FILES.length - 1) {
        currentIndex += 1;
      } else {
        currentIndex = 0;
      }
      return this.current();
    },
    previous: function() {
      if (currentIndex > 0) {
        currentIndex -= 1;
      } else {
        currentIndex = FILES.length - 1;
      }
      return this.current();
    }
  };

  viewer.on('load', function() {
    return toggleLoading(false);
  });

  viewer.attr('src', "images/" + (Images.current()));

  $('#slide-count').text(FILES.length);

  sizeToFit = function() {
    return viewer.toggleClass("size-to-fit");
  };

  toggleLoading = function(towards) {
    if (towards == null) {
      towards = true;
    }
    return viewer.toggleClass('loading', towards);
  };

  viewer.click(sizeToFit);

  $(document).keydown(function(e) {
    if (e.keyCode === 39) {
      toggleLoading();
      viewer.attr('src', "images/" + (Images.next()));
      if (viewer[0].complete) {
        toggleLoading(false);
      }
    }
    if (e.keyCode === 37) {
      toggleLoading();
      viewer.attr('src', "images/" + (Images.previous()));
      if (viewer[0].complete) {
        return toggleLoading(false);
      }
    }
  });

}).call(this);
